/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const teacherservice_Logic = require('./code/teacherservice-logic');

class DictService extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'TeacherService', async (request, next) => {
            await teacherservice_Logic({
                request
            });
            return next();
        });

        return super.init();
    }
}


module.exports = {
    DictService
};